// Generates `lib/src/text/unicode_data.g.dart` from the Unicode Character
// Database files in `tool/ucd/`.
//
//   dart run tool/gen_unicode_tables.dart
//
// The UCD files are fetched by `tool/fetch_ucd.sh`. They are NOT checked in —
// the generated Dart is, so building this package never touches the network.
//
// Everything is emitted as sorted, flat range tables searched with a binary
// scan. That form was chosen over a switch or a map because the shaper queries
// it once per codepoint per shaping call: ~11 comparisons beats a hash, and it
// costs 4 words per range instead of 2 per codepoint.
import 'dart:io';

void main(List<String> args) {
  final ucd = Directory('tool/ucd');
  if (!ucd.existsSync()) {
    stderr.writeln('tool/ucd/ missing — run tool/fetch_ucd.sh first.');
    exit(1);
  }

  final gc = _parseUnicodeData('tool/ucd/UnicodeData.txt');
  final joining = _parseArabicShaping(
    'tool/ucd/ArabicShaping.txt',
    gc.category,
  );
  final norm = _parseNormalization('tool/ucd/UnicodeData.txt', gc.combining);
  final scriptNames = <String>[];
  final scripts = _parseScripts('tool/ucd/Scripts.txt', scriptNames);
  final brackets = _parseBidiBrackets('tool/ucd/BidiBrackets.txt');
  final version = _detectVersion();

  final b = StringBuffer()
    ..writeln('// GENERATED by tool/gen_unicode_tables.dart — do not edit.')
    ..writeln('// Unicode Character Database $version.')
    ..writeln('//')
    ..writeln(
      '// Range tables are sorted and disjoint; `_lookup` binary-searches',
    )
    ..writeln(
      '// them. Each entry is (start, end, value) flattened into one list so',
    )
    ..writeln('// the whole table is a single contiguous allocation.')
    ..writeln("library;")
    ..writeln()
    ..writeln("import 'dart:typed_data';")
    ..writeln()
    ..writeln("/// The UCD revision these tables were generated from.")
    ..writeln("const String unicodeVersion = '$version';")
    ..writeln();

  _emitTable(
    b,
    'joiningTypeRanges',
    joining,
    comment: '''
/// Arabic joining type per codepoint — `ArabicShaping.txt`, with the derived
/// default applied: an unlisted codepoint whose general category is Mn, Me or
/// Cf is Transparent (5), and everything else is Non_Joining (0).
///
/// Transparent is the class naive shapers forget. A combining mark between two
/// letters must NOT break their join, so the joining state machine has to look
/// *through* it. Miss that and every Kurdish word carrying a diacritic loses
/// its connections.''',
  );

  _emitTable(
    b,
    'generalCategoryRanges',
    gc.ranges,
    comment: '''
/// Unicode general category, narrowed to the six values the shaper branches on:
/// 0 unassigned · 1 Mn · 2 Mc · 3 Me · 4 Nd · 5 Cf · 6 everything else.''',
  );

  _emitTable(
    b,
    'bidiClassRanges',
    gc.bidiRanges,
    comment: '''
/// UAX #9 bidirectional character type. Values index [bidiClassNames].''',
  );

  _emitTable(
    b,
    'bidiBracketRanges',
    brackets,
    comment: '''
/// UAX #9 BD14/BD15 paired brackets — `BidiBrackets.txt`.
///
/// The value packs both halves of the property the N0 rule needs:
/// `paired << 2 | type`, type 1 = Open, 2 = Close. Packing lets this share the
/// ordinary range table and its binary search instead of carrying a parallel
/// map; 0 (no bracket) can never collide because every paired codepoint is
/// non-zero.''',
  );

  _emitTable(
    b,
    'combiningClassRanges',
    gc.combiningRanges,
    comment: '''
/// Canonical_Combining_Class — `UnicodeData.txt` field 3.
///
/// The normalizer sorts a run of marks by this value before shaping, because
/// two spellings of the same vowelled word must produce the same glyphs: a
/// shadda typed before a kasra and one typed after it are canonically
/// equivalent, and a shaper that leaves them in typing order hands GSUB two
/// different sequences and gets two different results.''',
  );

  _emitTable(
    b,
    'scriptRanges',
    scripts,
    comment: '''
/// Unicode Script property — `Scripts.txt`. Values index [scriptNames].
///
/// Kept as long Unicode names rather than pre-resolved OpenType tags: the
/// script→`arab`/`latn`/`dev2` mapping is a *layout* decision (Devanagari wants
/// the v2 tag, Hiragana and Katakana collapse to one tag), and burning it into
/// a generated table would put that policy out of reach of the itemizer.''',
  );

  _emitList(
    b,
    'canonicalDecompositions',
    norm.decompositions,
    comment: '''
/// Canonical decompositions as (codepoint, first, second) triples sorted by
/// codepoint, with second = -1 for a singleton.
///
/// Compatibility decompositions — the `<font>`, `<circle>`, `<compat>` … forms —
/// are deliberately absent. NFKC would fold ﷼ to ر ي ا ل and a superscript ² to
/// a plain 2; a document engine that did that would be rewriting the text it
/// was handed.''',
  );

  _emitList(
    b,
    'canonicalCompositionPairs',
    norm.compositionPairs,
    comment: '''
/// Canonical compositions as (first, second, composed) triples, sorted by
/// (first, second) for binary search.
///
/// This is NFC's composition set, not a raw inversion of the decompositions:
/// singletons, non-starter decompositions and the frozen script-specific
/// exclusion list are all removed. Composing a character the exclusion list
/// forbids would silently change a Devanagari or Hebrew document's spelling.''',
  );

  b
    ..writeln()
    ..writeln('/// UAX #9 class names, in the order the numeric values use.')
    ..writeln('const List<String> bidiClassNames = <String>[')
    ..writeln("  ${_bidiOrder.map((s) => "'$s'").join(', ')},")
    ..writeln('];')
    ..writeln()
    ..writeln('/// Unicode script names, in the order [scriptRanges] indexes.')
    ..writeln('/// Index 0 is `Unknown`, the value an unlisted codepoint gets.')
    ..writeln('const List<String> scriptNames = <String>[');
  for (var i = 0; i < scriptNames.length; i += 6) {
    b.writeln(
      '  ${scriptNames.skip(i).take(6).map((s) => "'$s'").join(', ')},',
    );
  }
  b
    ..writeln('];')
    ..writeln()
    ..writeln(_lookupFn);

  File('lib/src/text/unicode_data.g.dart').writeAsStringSync(b.toString());
  stdout.writeln(
    'wrote lib/src/text/unicode_data.g.dart — '
    'joining ${joining.length ~/ 3} ranges, '
    'category ${gc.ranges.length ~/ 3}, '
    'bidi ${gc.bidiRanges.length ~/ 3}, '
    'brackets ${brackets.length ~/ 3}, '
    'combining ${gc.combiningRanges.length ~/ 3}, '
    'decompositions ${norm.decompositions.length ~/ 3}, '
    'compositions ${norm.compositionPairs.length ~/ 3}, '
    'script ${scripts.length ~/ 3} in ${scriptNames.length} scripts '
    '(UCD $version)',
  );
}

String _detectVersion() {
  final f = File('tool/ucd/ArabicShaping.txt');
  final head = f.readAsLinesSync().take(3).join(' ');
  final m = RegExp(r'(\d+\.\d+\.\d+)').firstMatch(head);
  return m?.group(1) ?? 'unknown';
}

const _bidiOrder = [
  'L', 'R', 'AL', 'EN', 'ES', 'ET', 'AN', 'CS', 'NSM', 'BN', //
  'B', 'S', 'WS', 'ON', 'LRE', 'RLE', 'LRO', 'RLO', 'PDF', //
  'LRI', 'RLI', 'FSI', 'PDI',
];

class _Ucd {
  _Ucd(
    this.category,
    this.bidi,
    this.combining,
    this.ranges,
    this.bidiRanges,
    this.combiningRanges,
  );

  final Map<int, int> category;
  final Map<int, int> bidi;
  final Map<int, int> combining;
  final List<int> ranges;
  final List<int> bidiRanges;
  final List<int> combiningRanges;
}

class _Norm {
  _Norm(this.decompositions, this.compositionPairs);

  final List<int> decompositions;
  final List<int> compositionPairs;
}

/// `CompositionExclusions.txt` sections 1 and 2 — the exclusions that cannot be
/// derived from `UnicodeData.txt` alone.
///
/// Sections 3 (singletons) and 4 (non-starter decompositions) ARE derivable and
/// are computed below rather than listed. This list is carried literally because
/// Unicode's stability policy freezes it: no codepoint may be added to or
/// removed from it in any future version, so it cannot go stale. Fetching one
/// more UCD file to read a frozen constant would be the more fragile choice, not
/// the safer one.
const Set<int> _compositionExclusions = <int>{
  // §1 script specifics
  0x0958, 0x0959, 0x095A, 0x095B, 0x095C, 0x095D, 0x095E, 0x095F,
  0x09DC, 0x09DD, 0x09DF, 0x0A33, 0x0A36, 0x0A59, 0x0A5A, 0x0A5B,
  0x0A5E, 0x0B5C, 0x0B5D, 0x0F43, 0x0F4D, 0x0F52, 0x0F57, 0x0F5C,
  0x0F69, 0x0F76, 0x0F78, 0x0F93, 0x0F9D, 0x0FA2, 0x0FA7, 0x0FAC,
  0x0FB9, 0xFB1D, 0xFB1F, 0xFB2A, 0xFB2B, 0xFB2C, 0xFB2D, 0xFB2E,
  0xFB2F, 0xFB30, 0xFB31, 0xFB32, 0xFB33, 0xFB34, 0xFB35, 0xFB36,
  0xFB38, 0xFB39, 0xFB3A, 0xFB3B, 0xFB3C, 0xFB3E, 0xFB40, 0xFB41,
  0xFB43, 0xFB44, 0xFB46, 0xFB47, 0xFB48, 0xFB49, 0xFB4A, 0xFB4B,
  0xFB4C, 0xFB4D, 0xFB4E,
  // §2 post-composition-version precomposed characters
  0x2ADC,
  0x1D15E, 0x1D15F, 0x1D160, 0x1D161, 0x1D162, 0x1D163, 0x1D164,
  0x1D1BB, 0x1D1BC, 0x1D1BD, 0x1D1BE, 0x1D1BF, 0x1D1C0,
};

/// Builds the canonical decomposition and composition tables.
///
/// The composition set is NOT the inverse of the decomposition set. Three
/// classes of decomposition must never be recomposed, or normalizing a string
/// would change what it says:
///
///  * singletons (one target codepoint),
///  * decompositions whose first codepoint is a non-starter,
///  * the frozen [_compositionExclusions] list.
_Norm _parseNormalization(String path, Map<int, int> combining) {
  final decomposition = <int, List<int>>{};

  for (final line in File(path).readAsLinesSync()) {
    if (line.isEmpty) continue;
    final f = line.split(';');
    if (f.length < 6) continue;
    final field = f[5].trim();
    // A leading `<tag>` marks a COMPATIBILITY decomposition. NFKC would fold
    // ﷼ to ر ي ا ل and a superscript ² to a plain 2 — a document engine that
    // did that would be rewriting the text it was given.
    if (field.isEmpty || field.startsWith('<')) continue;
    final parts = field
        .split(' ')
        .where((s) => s.isNotEmpty)
        .map((s) => int.parse(s, radix: 16))
        .toList();
    if (parts.isEmpty || parts.length > 2) continue;
    decomposition[int.parse(f[0], radix: 16)] = parts;
  }

  final keys = decomposition.keys.toList()..sort();
  final data = <int>[];
  final pairs = <List<int>>[];

  for (final cp in keys) {
    final d = decomposition[cp]!;
    data
      ..add(cp)
      ..add(d[0])
      ..add(d.length > 1 ? d[1] : -1);

    if (d.length != 2) continue;
    if ((combining[d[0]] ?? 0) != 0) continue;
    if (_compositionExclusions.contains(cp)) continue;
    pairs.add([d[0], d[1], cp]);
  }

  pairs.sort((a, b) => a[0] != b[0] ? a[0] - b[0] : a[1] - b[1]);

  return _Norm(data, [for (final p in pairs) ...p]);
}

/// Narrowed general category codes — see the doc comment emitted above.
int _gcCode(String s) => switch (s) {
  'Mn' => 1,
  'Mc' => 2,
  'Me' => 3,
  'Nd' => 4,
  'Cf' => 5,
  _ => 6,
};

_Ucd _parseUnicodeData(String path) {
  final category = <int, int>{};
  final bidi = <int, int>{};
  final combining = <int, int>{};

  // UnicodeData.txt encodes large blocks as a "First>"/"Last>" pair rather than
  // one line per codepoint. Expanding those is required — CJK and the private
  // use areas are only ever expressed that way.
  int? pendingStart;
  var pendingGc = 6;
  var pendingBidi = 0;

  for (final line in File(path).readAsLinesSync()) {
    if (line.isEmpty) continue;
    final f = line.split(';');
    if (f.length < 5) continue;
    final cp = int.parse(f[0], radix: 16);
    final name = f[1];
    final gc = _gcCode(f[2]);
    final ccc = int.tryParse(f[3]) ?? 0;
    final bc = _bidiOrder.indexOf(f[4]);
    final bcv = bc < 0 ? 13 : bc; // unknown → ON

    if (name.endsWith(', First>')) {
      pendingStart = cp;
      pendingGc = gc;
      pendingBidi = bcv;
      continue;
    }
    if (name.endsWith(', Last>') && pendingStart != null) {
      // A First/Last block never carries a combining class — every one of them
      // is CJK, Hangul, Tangut, private use or a surrogate range, all ccc 0.
      for (var c = pendingStart; c <= cp; c++) {
        category[c] = pendingGc;
        bidi[c] = pendingBidi;
      }
      pendingStart = null;
      continue;
    }
    category[cp] = gc;
    bidi[cp] = bcv;
    if (ccc != 0) combining[cp] = ccc;
  }

  // UAX #9 assigns defaults by block to UNASSIGNED codepoints — a font may be
  // asked to lay out an unassigned codepoint from a future Unicode, and it must
  // still get RTL treatment inside an Arabic block or the paragraph flips.
  const defaults = <(int, int, String)>[
    (0x0600, 0x07BF, 'AL'),
    (0x0860, 0x08FF, 'AL'),
    (0xFB50, 0xFDCF, 'AL'),
    (0xFDF0, 0xFDFF, 'AL'),
    (0xFE70, 0xFEFF, 'AL'),
    (0x10D00, 0x10D3F, 'AL'),
    (0x10EC0, 0x10EFF, 'AL'),
    (0x10F30, 0x10F6F, 'AL'),
    (0x1EC70, 0x1ECBF, 'AL'),
    (0x1ED00, 0x1ED4F, 'AL'),
    (0x1EE00, 0x1EEFF, 'AL'),
    (0x0590, 0x05FF, 'R'),
    (0x07C0, 0x085F, 'R'),
    (0xFB1D, 0xFB4F, 'R'),
    (0x10800, 0x10CFF, 'R'),
    (0x10D40, 0x10EBF, 'R'),
    (0x10F00, 0x10F2F, 'R'),
    (0x10F70, 0x10FFF, 'R'),
    (0x1E800, 0x1EC6F, 'R'),
    (0x1ECC0, 0x1ECFF, 'R'),
    (0x1ED50, 0x1EDFF, 'R'),
    (0x1EF00, 0x1EFFF, 'R'),
    (0x20A0, 0x20CF, 'ET'),
  ];
  for (final (lo, hi, cls) in defaults) {
    final v = _bidiOrder.indexOf(cls);
    for (var c = lo; c <= hi; c++) {
      bidi.putIfAbsent(c, () => v);
    }
  }

  return _Ucd(
    category,
    bidi,
    combining,
    _toRanges(category, defaultValue: 0),
    _toRanges(bidi, defaultValue: 0),
    _toRanges(combining, defaultValue: 0),
  );
}

List<int> _parseArabicShaping(String path, Map<int, int> category) {
  const codes = {'U': 0, 'L': 1, 'R': 2, 'D': 3, 'C': 4, 'T': 5};
  final joining = <int, int>{};

  for (final raw in File(path).readAsLinesSync()) {
    final line = raw.split('#').first.trim();
    if (line.isEmpty) continue;
    final f = line.split(';');
    if (f.length < 3) continue;
    final cp = int.tryParse(f[0].trim(), radix: 16);
    final t = codes[f[2].trim()];
    if (cp == null || t == null) continue;
    joining[cp] = t;
  }

  // The derived default: anything with category Mn, Me or Cf that the file does
  // not list is Transparent. UTR #53 states this; ArabicShaping.txt itself only
  // enumerates the Arabic-script exceptions.
  category.forEach((cp, gc) {
    if (gc == 1 || gc == 3 || gc == 5) {
      joining.putIfAbsent(cp, () => 5);
    }
  });

  return _toRanges(joining, defaultValue: 0);
}

/// Parses `Scripts.txt` into a (start, end, scriptId) table, filling [namesOut]
/// with the id→name mapping.
///
/// Unlike the other tables this one is built from the file's own ranges instead
/// of a per-codepoint map: Scripts.txt covers every assigned codepoint, and
/// expanding CJK and the private use areas one codepoint at a time to collapse
/// them again costs a second of startup for an identical result.
List<int> _parseScripts(String path, List<String> namesOut) {
  final raw = <(int, int, String)>[];
  final names = <String>{};

  for (final rawLine in File(path).readAsLinesSync()) {
    final line = rawLine.split('#').first.trim();
    if (line.isEmpty) continue;
    final f = line.split(';');
    if (f.length < 2) continue;
    final bounds = f[0].trim().split('..');
    final lo = int.tryParse(bounds[0], radix: 16);
    if (lo == null) continue;
    final hi = bounds.length > 1 ? int.parse(bounds[1], radix: 16) : lo;
    final name = f[1].trim();
    raw.add((lo, hi, name));
    names.add(name);
  }

  // Unknown takes id 0 so it doubles as `lookupRange`'s not-found value; the
  // rest are alphabetical purely so the generated file is stable across runs.
  final sorted = names.toList()..sort();
  sorted.remove('Unknown');
  namesOut
    ..clear()
    ..add('Unknown')
    ..addAll(sorted);
  final id = <String, int>{
    for (var i = 0; i < namesOut.length; i++) namesOut[i]: i,
  };

  raw.sort((a, b) => a.$1.compareTo(b.$1));
  final out = <int>[];
  for (final (lo, hi, name) in raw) {
    final v = id[name]!;
    if (v == 0) continue;
    final n = out.length;
    if (n >= 3 && out[n - 1] == v && out[n - 2] + 1 == lo) {
      out[n - 2] = hi;
    } else {
      out
        ..add(lo)
        ..add(hi)
        ..add(v);
    }
  }
  return out;
}

/// Parses `BidiBrackets.txt` into (cp, cp, paired << 2 | type) entries.
///
/// The pairs are what rule N0 needs to keep `(ARABIC)` from turning inside out
/// around a Latin word; without them a parenthesised clause in a mixed-direction
/// invoice line renders with its brackets swapped.
List<int> _parseBidiBrackets(String path) {
  final map = <int, int>{};
  for (final rawLine in File(path).readAsLinesSync()) {
    final line = rawLine.split('#').first.trim();
    if (line.isEmpty) continue;
    final f = line.split(';');
    if (f.length < 3) continue;
    final cp = int.tryParse(f[0].trim(), radix: 16);
    final paired = int.tryParse(f[1].trim(), radix: 16);
    if (cp == null || paired == null) continue;
    final type = switch (f[2].trim()) {
      'o' => 1,
      'c' => 2,
      _ => 0,
    };
    if (type == 0) continue;
    map[cp] = (paired << 2) | type;
  }
  return _toRanges(map, defaultValue: 0);
}

/// Collapses a sparse codepoint→value map into a flat (start, end, value) list,
/// dropping runs that equal [defaultValue].
List<int> _toRanges(Map<int, int> map, {required int defaultValue}) {
  final keys = map.keys.toList()..sort();
  final out = <int>[];
  var i = 0;
  while (i < keys.length) {
    final v = map[keys[i]]!;
    if (v == defaultValue) {
      i++;
      continue;
    }
    final start = keys[i];
    var end = start;
    while (i + 1 < keys.length &&
        keys[i + 1] == end + 1 &&
        map[keys[i + 1]] == v) {
      end = keys[++i];
    }
    out
      ..add(start)
      ..add(end)
      ..add(v);
    i++;
  }
  return out;
}

void _emitTable(
  StringBuffer b,
  String name,
  List<int> ranges, {
  required String comment,
}) {
  b
    ..writeln()
    ..writeln(comment)
    ..writeln('final Int32List $name = Int32List.fromList(const <int>[');
  for (var i = 0; i < ranges.length; i += 3 * 8) {
    final chunk = ranges.skip(i).take(3 * 8).join(', ');
    b.writeln('  $chunk,');
  }
  b.writeln(']);');
}

/// The same as [_emitTable] for a flat list that is not a range table.
void _emitList(
  StringBuffer b,
  String name,
  List<int> values, {
  required String comment,
}) {
  b
    ..writeln()
    ..writeln(comment)
    ..writeln('final Int32List $name = Int32List.fromList(const <int>[');
  for (var i = 0; i < values.length; i += 24) {
    b.writeln('  ${values.skip(i).take(24).join(', ')},');
  }
  b.writeln(']);');
}

const _lookupFn = '''
/// Binary-searches a flat (start, end, value) range table.
///
/// Returns 0 — the table's default — when [codepoint] falls in no range.
int lookupRange(Int32List table, int codepoint) {
  var lo = 0;
  var hi = table.length ~/ 3 - 1;
  while (lo <= hi) {
    final mid = (lo + hi) >> 1;
    final i = mid * 3;
    if (codepoint < table[i]) {
      hi = mid - 1;
    } else if (codepoint > table[i + 1]) {
      lo = mid + 1;
    } else {
      return table[i + 2];
    }
  }
  return 0;
}
''';
