// THE GATE.
//
// Every glyph id and every position this engine produces is compared against
// HarfBuzz — the reference implementation of OpenType shaping — for the same
// string and the same font. Where we differ, we are wrong. There is no second
// opinion to appeal to and no "looks right" escape hatch.
//
// The corpus is generated by `tool/gen_harfbuzz_corpus.py` and checked in, so
// this test runs with no Python, no native library and no network. Regenerate
// it when the font changes:
//
//     python3 tool/gen_harfbuzz_corpus.py
//
// WHY GLYPH-LEVEL AND NOT TEXT EXTRACTION. A PDF can carry a perfect
// `/ActualText` string over completely garbled glyphs — extraction proves the
// ToUnicode CMap and nothing whatsoever about shaping. And a human cannot tell
// `uni06B5.medi` from `uni06B5.init` at 10 pt, which is exactly the class of
// error that ships. Only glyph ids settle it.
@Tags(['shaping'])
library;

import 'dart:convert';
import 'dart:io';

import 'package:payv/payv.dart';
import 'package:test/test.dart';

/// Cases whose failure means the package's central claim is false. If any of
/// these regress, Kurdish is broken and no other passing test compensates.
const Set<String> kSoraniCriticalCases = {
  're-isol',
  're-fina',
  're-init',
  're-word',
  'lam-v-isol',
  'lam-v-init',
  'lam-v-medi',
  'lam-v-fina',
  'ae-isol',
  'ae-fina',
  'ye-isol',
  'ye-init',
  'ye-medi',
  'ye-fina',
  'lam-v-alef',
  'palawtn',
  'rega',
  'jmara',
  'gorini',
};

void main() {
  final fixture = File('test/fixtures/harfbuzz_golden.json');
  if (!fixture.existsSync()) {
    throw StateError(
      'test/fixtures/harfbuzz_golden.json is missing — run '
      'python3 tool/gen_harfbuzz_corpus.py',
    );
  }

  final golden = jsonDecode(fixture.readAsStringSync()) as Map<String, dynamic>;
  final cases = (golden['cases'] as List).cast<Map<String, dynamic>>();

  final fontFile = File('test/fonts/Vazirmatn.ttf');
  if (!fontFile.existsSync()) {
    throw StateError('test font not found at ${fontFile.path}');
  }
  final font = OpenTypeFont.parse(fontFile.readAsBytesSync());
  final shaper = Shaper(font);

  group(
    'HarfBuzz parity (${golden['harfbuzzVersion']}, ${golden['font']})',
    () {
      test(
        'the font under test matches the one the corpus was generated from',
        () {
          expect(font.unitsPerEm, golden['unitsPerEm']);
        },
      );

      for (final c in cases) {
        final id = c['id'] as String;
        final text = c['text'] as String;
        final note = c['note'] as String;
        final expected = (c['glyphs'] as List).cast<Map<String, dynamic>>();
        final critical = kSoraniCriticalCases.contains(id);

        test('$id — $note${critical ? "  [SORANI-CRITICAL]" : ""}', () {
          final run = shaper.shape(text);

          final actual = [
            for (var i = 0; i < run.length; i++)
              {
                'gid': run.infos[i].glyphId,
                'cluster': run.infos[i].cluster,
                'xAdvance': run.positions[i].xAdvance,
                'yAdvance': run.positions[i].yAdvance,
                'xOffset': run.positions[i].xOffset,
                'yOffset': run.positions[i].yOffset,
              },
          ];

          final want = [
            for (final g in expected)
              {
                'gid': g['gid'],
                'cluster': g['cluster'],
                'xAdvance': g['xAdvance'],
                'yAdvance': g['yAdvance'],
                'xOffset': g['xOffset'],
                'yOffset': g['yOffset'],
              },
          ];

          expect(actual, want, reason: _diff(text, expected, run));
        });
      }

      test('direction is resolved the same way HarfBuzz resolves it', () {
        for (final c in cases) {
          final run = shaper.shape(c['text'] as String);
          final want = c['direction'] == 'rtl'
              ? TextDirection.rtl
              : TextDirection.ltr;
          expect(run.direction, want, reason: 'case ${c["id"]} (${c["text"]})');
        }
      });
    },
  );

  group('the claim this package is built on', () {
    // These assertions are the package's thesis stated as code. They do not
    // depend on the corpus: they check directly that we produce glyphs which
    // NO amount of codepoint mapping could have produced.
    test('reaches glyphs that have no Unicode codepoint', () {
      final reachable = <int>{
        for (var cp = 0; cp <= 0x10FFFF; cp++)
          if (cp < 0x3000 ||
              (cp >= 0xFB50 && cp <= 0xFEFF) ||
              (cp >= 0x10000 && cp <= 0x10FFF))
            font.glyphForCodepoint(cp),
      }..remove(0);

      // `پاڵاوتن` — the ڵ+ا ligature. There is no codepoint for it anywhere in
      // Unicode, so if the shaper produced it, it came out of GSUB.
      final palawtn = shaper.shape('پاڵاوتن');
      final gids = palawtn.infos.map((i) => i.glyphId).toSet();
      final unreachable = gids.difference(reachable);

      expect(
        unreachable,
        isNotEmpty,
        reason:
            'پاڵاوتن should contain at least one glyph unreachable through '
            'cmap (the ڵ+ا ligature). If this is empty, we are doing '
            'presentation-form mapping and the whole package is pointless.',
      );
    });

    test('the four form-less Sorani letters shape distinctly per position', () {
      // ڵ is dual-joining: isolated, initial, medial and final must all be
      // DIFFERENT glyphs. A presentation-form library returns the same glyph
      // (or nothing) for all four, because U+06B5 has no forms in Unicode.
      for (final (letter, name) in [('ڵ', 'ڵ U+06B5'), ('ێ', 'ێ U+06CE')]) {
        final isol = _gids(shaper.shape(letter));
        final init = _gids(shaper.shape('$letterب')); // + ب
        final medi = _gids(shaper.shape('ب$letterب'));
        final fina = _gids(shaper.shape('ب$letter'));

        final forms = {isol.first, init.first, medi[1], fina[1]};
        expect(
          forms.length,
          greaterThanOrEqualTo(3),
          reason:
              '$name must take distinct contextual shapes; got $forms. '
              'Fewer than 3 distinct glyphs means the joining state machine '
              'is not reaching the font\'s GSUB alternates.',
        );
      }
    });

    test('never emits a Unicode presentation form as a source codepoint', () {
      // Our own sanity check against regressing into the very technique this
      // package exists to replace: no codepoint we feed the cmap should ever
      // come from the presentation-form blocks.
      for (final c in cases) {
        final run = shaper.shape(c['text'] as String);
        for (final info in run.infos) {
          final cp = info.codepoint;
          expect(
            cp >= 0xFB50 && cp <= 0xFEFF,
            isFalse,
            reason:
                'case ${c["id"]}: source codepoint U+${cp.toRadixString(16)} '
                'is a presentation form. Shaping must start from the ORIGINAL '
                'text, never from remapped forms.',
          );
        }
      }
    });
  });
}

List<int> _gids(ShapedRun r) => r.infos.map((i) => i.glyphId).toList();

/// A side-by-side dump, because a raw list mismatch on 13 glyphs is unreadable.
String _diff(
  String text,
  List<Map<String, dynamic>> expected,
  ShapedRun actual,
) {
  final b = StringBuffer()
    ..writeln('\nshaping "$text"')
    ..writeln('  ${"HARFBUZZ".padRight(46)}PAYV')
    ..writeln('  ${"-" * 46}${"-" * 40}');

  final n = expected.length > actual.length ? expected.length : actual.length;
  for (var i = 0; i < n; i++) {
    final e = i < expected.length ? expected[i] : null;
    final want = e == null
        ? ''
        : 'gid ${e["gid"]} ${e["name"]} cl${e["cluster"]} '
              'adv ${e["xAdvance"]} off(${e["xOffset"]},${e["yOffset"]})';
    final got = i < actual.length
        ? 'gid ${actual.infos[i].glyphId} cl${actual.infos[i].cluster} '
              'adv ${actual.positions[i].xAdvance} '
              'off(${actual.positions[i].xOffset},${actual.positions[i].yOffset})'
        : '';
    final same =
        want.isNotEmpty &&
        got.isNotEmpty &&
        e!['gid'] == actual.infos[i].glyphId &&
        e['xAdvance'] == actual.positions[i].xAdvance;
    b.writeln('${same ? "  " : "✗ "}${want.padRight(46)}$got');
  }
  return b.toString();
}
